# Generated by Django 3.1.7 on 2021-02-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, choices=[(0, 'Adult'), (1, 'Child'), (2, 'Teenager')], null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'Male'), (0, 'Female')], null=True)),
                ('name_en', models.TextField(blank=True, null=True)),
                ('name_zh', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'actors',
            },
        ),
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.IntegerField(blank=True, null=True)),
                ('character', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'characters',
            },
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.IntegerField(blank=True, null=True)),
                ('hkmdb_id', models.IntegerField(blank=True, null=True)),
                ('name_en', models.TextField(blank=True, null=True)),
                ('name_zh', models.TextField(blank=True, null=True)),
                ('visible', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'films',
            },
        ),
        migrations.CreateModel(
            name='Sentences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.IntegerField(blank=True, null=True)),
                ('film_id', models.IntegerField(blank=True, null=True)),
                ('media_code', models.IntegerField(blank=True, null=True)),
                ('media_part', models.TextField(blank=True, null=True)),
                ('timestamp_duration_ms', models.IntegerField(blank=True, null=True)),
                ('timestamp_ends_at_ms', models.IntegerField(blank=True, null=True)),
                ('timestamp_starts_at_ms', models.IntegerField(blank=True, null=True)),
                ('transcription', models.TextField(blank=True, null=True)),
                ('annotation_auto', models.TextField(blank=True, null=True)),
                ('annotation_string', models.TextField(blank=True, null=True)),
                ('alpha', models.TextField(blank=True, null=True)),
                ('characters_string', models.TextField(blank=True, null=True)),
                ('num_characters', models.IntegerField(blank=True, null=True)),
                ('num_tokens', models.IntegerField(blank=True, null=True)),
                ('orth', models.TextField(blank=True, null=True)),
                ('pron', models.TextField(blank=True, null=True)),
                ('tag', models.TextField(blank=True, null=True)),
                ('tokens_string', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sentences',
            },
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_id', models.IntegerField(blank=True, null=True)),
                ('sentence_id', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tokens',
            },
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orth', models.TextField(blank=True, null=True)),
                ('tag', models.TextField(blank=True, null=True)),
                ('pron', models.TextField(blank=True, null=True)),
                ('alpha', models.TextField(blank=True, null=True)),
                ('freq', models.IntegerField(blank=True, null=True)),
                ('freq_adult', models.IntegerField(blank=True, null=True)),
                ('freq_child', models.IntegerField(blank=True, null=True)),
                ('freq_teenager', models.IntegerField(blank=True, null=True)),
                ('freq_female', models.IntegerField(blank=True, null=True)),
                ('freq_male', models.IntegerField(blank=True, null=True)),
                ('freq_comedy', models.IntegerField(blank=True, null=True)),
                ('freq_crime', models.IntegerField(blank=True, null=True)),
                ('freq_drama', models.IntegerField(blank=True, null=True)),
                ('freq_1943', models.IntegerField(blank=True, null=True)),
                ('freq_1947', models.IntegerField(blank=True, null=True)),
                ('freq_1948', models.IntegerField(blank=True, null=True)),
                ('freq_1950', models.IntegerField(blank=True, null=True)),
                ('freq_1951', models.IntegerField(blank=True, null=True)),
                ('freq_1952', models.IntegerField(blank=True, null=True)),
                ('freq_1953', models.IntegerField(blank=True, null=True)),
                ('freq_1954', models.IntegerField(blank=True, null=True)),
                ('freq_1955', models.IntegerField(blank=True, null=True)),
                ('freq_1956', models.IntegerField(blank=True, null=True)),
                ('freq_1957', models.IntegerField(blank=True, null=True)),
                ('freq_1958', models.IntegerField(blank=True, null=True)),
                ('freq_1959', models.IntegerField(blank=True, null=True)),
                ('freq_1960', models.IntegerField(blank=True, null=True)),
                ('freq_1961', models.IntegerField(blank=True, null=True)),
                ('freq_1962', models.IntegerField(blank=True, null=True)),
                ('freq_1963', models.IntegerField(blank=True, null=True)),
                ('freq_1964', models.IntegerField(blank=True, null=True)),
                ('freq_1965', models.IntegerField(blank=True, null=True)),
                ('freq_1966', models.IntegerField(blank=True, null=True)),
                ('freq_1967', models.IntegerField(blank=True, null=True)),
                ('freq_1968', models.IntegerField(blank=True, null=True)),
                ('freq_1969', models.IntegerField(blank=True, null=True)),
                ('freq_1970', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'words',
            },
        ),
    ]
